name: Publish to PyPI
on:
  release:
    types: [prereleased]

jobs:
  test:
    name:  Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: "Set up Python"
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5
        with:
          version: "0.6.1"

      - name: Publish
        run: |
          uv build
          uv publish --index testpypi
