name: Publish to PyPI
on:
  release:
    types: [prereleased]

jobs:
  test:
    name:  Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.1"

      - name: Publish
        run: |
          uv build
          uv publish --index testpypi
